### ISSUE TITLE
Mac installer for extensions won't install when Inkscape is installed in non-default location

### ISSUE THREAD

**Issue by composerjk** [evil-mad/axidraw#10]
[ This may not be worth fixing since it may be an atypical setup, but wanted to mention, just in case. ]

On my Mac, Inkscape is installed in `~/Applications/` instead of the top-level `/Applications/`.

The AxiDraw_V1.0.2.pkg installer complains about requiring Inkscape 0.91 or higher since it can't locate Inkscape. There's no option to specify another location to check for Inkscape.

**Workaround:** Move Inkscape.app into `/Applications/`

**Comment by oskay** [comment]
Our documentation says "This installer requires Inkscape 0.91, installed in your main applications folder."  I suspect that either (1) using the easy install, or (2) moving Inkscape to /Applications temporarily or (3) requiring a manual installation are acceptable in the few cases where someone has it installed in a different location.

**Comment by composerjk** [comment]
Agreed. That's why I mentioned it may not really need fixing. And, I'll admit I forgot to go back to review the earlier documentation. Oops.

**Comment by oskay** [comment]
No worries. It's a tricky choice as to whether it's better to allow you to search for Inkscape (which solves some edge cases but adds complexity) or to require it in one place.
