### ISSUE TITLE
Axidraw makes odd sound when arm tries to extend to full length.

### ISSUE THREAD

**Issue by idesignwell** [evil-mad/axidraw#103]
When the body slides all the way to the bottom right corner, just before it would be flush, it makes an odd sound, and doesnt quite reach it. The arm itself will extend to the full length just fine, but for some reason its as if it's restricted just before the end. The unit is essentially brand new, I've had nothing but successful plots until I tried to do plot a contact sheet at 11x17. 

I don't want to damage the Axi by exploring too much here, so hopefully this is a newb question, I look forward to any help and thank you in advance.

**Comment by oskay** [comment]
This doesn't sound like a software issue at all -- please contact tech support.
