### ISSUE TITLE
Bad SVG causes bug in Plot optimization script - possible fix

### ISSUE THREAD

**Issue by duskvirkus** [evil-mad/axidraw#105]
## Bug

I have this svg file that I created using illustrator. I don't know what part of the svg is causing the problem but I get the following bug.

```
line 238, in plot_to_axidraw
    ad.effect()
  File "C:\Users\violet\AppData\Roaming\inkscape\extensions\axidraw_deps\axidrawinternal\axidraw.py", line 398, in effect
    self.plot_document()
  File "C:\Users\violet\AppData\Roaming\inkscape\extensions\axidraw_deps\axidrawinternal\axidraw.py", line 728, in plot_document
    asr.effect() # Run the reordering
  File "C:\Users\violet\AppData\Roaming\inkscape\extensions\axidraw_deps\axidrawinternal\axidraw_svg_reorder.py", line 200, in effect
    self.svg = self.parse_svg(self.svg, matCurrent)
  File "C:\Users\violet\AppData\Roaming\inkscape\extensions\axidraw_deps\axidrawinternal\axidraw_svg_reorder.py", line 347, in parse_svg
    node = self.parse_svg(node, matNew, visibility)
  File "C:\Users\violet\AppData\Roaming\inkscape\extensions\axidraw_deps\axidrawinternal\axidraw_svg_reorder.py", line 340, in parse_svg
    first_point[0], first_point[1], last_point[0], last_point[1] )
TypeError: 'NoneType' object is not subscriptable
```

Attached file: (gh won't let me attach an svg so just added the txt on the end so remove that)
[AxiDraw_reorder-bug.svg.txt](https://github.com/evil-mad/axidraw/files/6543777/AxiDraw_reorder-bug.svg.txt)

System Info: Windows 10, Inkscape 1.0.2-2 (e86c870879, 2021-01-15), AxiDraw Control v 2.7.0, Axi Draw V3 A3

## Quick Fix

My quick fix for this solution was to change
```python                      
                        coord_dict[id] = (start_plottable and end_plottable,
                            first_point[0], first_point[1], last_point[0], last_point[1] )
                        # Entry in group_dict is this node 
                        group_dict[id] = a_node
```
to
```python
                        if start_plottable and end_plottable and first_point and last_point:                       
                            coord_dict[id] = (start_plottable and end_plottable,
                                first_point[0], first_point[1], last_point[0], last_point[1] )
                            # Entry in group_dict is this node 
                            group_dict[id] = a_node
```
which seemed to have fixed the bug.

If you need context here's a link to the current block in the repo:
https://github.com/evil-mad/axidraw/blob/fd7f13e89fc25470c5474d9b9ec94ad1556adf51/inkscape%20driver/axidraw_svg_reorder.py#L339

Not the most elegant solution but didn't really know how to debug the issue without any easy way to do logging. Happy to make a pull request with this solution but if someone more familiar with the code base has a better idea then that's great too.

cc @oskay  (I think you wrote axidraw_svg_reorder.py)

**Comment by oskay** [comment]
Please try 2.7.1, available as a manual install for Windows, here: 
https://wiki.evilmadscientist.com/Axidraw_Software_Installation#Alternative_.28Manual.29_install

**Comment by oskay** [comment]
If that doesn't fix it there is also a slightly newer version that isn't yet uploaded.

**Comment by oskay** [comment]
And in any case, the likely issue is that you have "paths" in your document that don't have any path data.

**Comment by oskay** [comment]
Closing this due to lack of feedback and the likely-resolved status.

If this particular issue persists, please let us know.
