### ISSUE TITLE
pen doesn't go up and down anymore

### ISSUE THREAD

**Issue by Fredericordeiro** [evil-mad/axidraw#107]
I have a V3 model and use it simply for writing names. For no reason, in the middle of a name the pen is raised and never lowered to write. If I start a new name, it does the entire writing process but without the lowering and raising the pen, which makes it impossible to use it for what I need.
I've already tried to reinstall the system. Install on another computer and nothing. I'm desperate here because I need to deliver to a client this week. Has anyone been through this and could you help me please?

**Comment by oskay** [comment]
Please contact technical support; this doesn't sound like an issue in the software.
