### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by DaAwesomeP** [evil-mad/axidraw#109]
Hello!

I am setting up a lot of kiosk machines with the AxiDraw CLI and the Inkscape plugin! One thing that has been a struggle to manage centrally is that the Python package is not on [PyPi](https://pypi.org/). This would allow for anyone to install it just by running `pip install pyaxidraw`. More importantly, this makes grabbing or installing different versions much simpler since they will all be on PyPi. As I setup all of these machines to run long-term, it is difficult to install with pip via a ZIP archive since it has to download the entire archive and extract it just to check if there is a new version.

I am happy to contribute a GitHub Actions script in a pull request that would do this automatically when a new tag/release is created or assist in anything related to publishing or creating the package.

Thanks!
Perry

**Comment by oskay** [comment]
We are not planning to publish the AxiDraw software to PyPI in the near future.

If you are concerned about running long-term in kiosks, I would strongly advise you to pick a specific version and install it and all dependencies from a local copy, so that your setup is not disabled by API changes.

If you want to check for whether there's a new version, use the version check feature of the software. It is not actually necessary to download the full zip. (And, for what it's worth, the full zip is about 121 kB, as of the last release.)

I am curious what the use case is for using both the Inkscape plugin and the CLI.

**Comment by DaAwesomeP** [comment]
> If you are concerned about running long-term in kiosks, I would strongly advise you to pick a specific version and install it and all dependencies from a local copy, so that your setup is not disabled by API changes.

Yes, I have downloaded the package though I am trying to be careful about storing it since some of the parts of it are GPL.

On that note, is there a URL available to download a specific version? The normal URL (`https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip`) does not have a version number in it.

> If you want to check for whether there's a new version, use the version check feature of the software. It is not actually necessary to download the full zip. (And, for what it's worth, the full zip is about 121 kB, as of the last release.)

Yeah, it was really pip that was taking a long time to process it.

> I am curious what the use case is for using both the Inkscape plugin and the CLI.

These kiosks are for students to use to draw whatever they wish. We want to offer all of the available methods so that they may use whatever they like best or fits their workflow (Inkscape, CLI, Python library, saxi, etc.). It's all being configured with SaltStack so that each machine is exactly the same. I am happy to share the repo when finished.

**Comment by oskay** [comment]
We previously used a different link per version, but had requests to use a consistent link instead, and did make that change. I suppose that what we need is both, really.

I'll begin adding version-specific links as well.

**Comment by DaAwesomeP** [comment]
Thank you very much!

**Comment by oskay** [comment]
API docs, as of this week's release, now include some archived version links.
