### ISSUE TITLE
Restrict the workspace (and configure a different home position)

### ISSUE THREAD

**Issue by martinmakesitwork** [evil-mad/axidraw#111]
Hi, 

i want to restrict the axidraw to work in a certain area.
My problem is: There are areas where the pen would crash if it would go over it.
Therefor i need zones of restriction or at least enabled zones. 
The second problem is: the home zone is such an area. So it would be great to be able to change the home position.

How can I solve these problems?

**Comment by oskay** [comment]
I'd suggest to use the Python Interactive API, for which you can specify the exact positions to travel to: https://axidraw.com/doc/py_api/

For the Home corner issue, is the "back right" corner, furthest along the X axis from Home, also a keep-out area?

**Comment by oskay** [comment]
If you would like to follow up on this issue, please do so. Otherwise, I will close it soon.
