### ISSUE TITLE
Small bug: After 'Plot', the Pen is moved to home, but not to the (full?) 'Up'-Position

### ISSUE THREAD

**Issue by schittli** [evil-mad/axidraw#115]
Good morning
I wish you a blessed new year.

Many thanks for the continued development of the AxiDraw software, especially the new usability of AxiDraw Control is great and the instructions are very clear and understandable.

_AxiDraw Control Version: 3.0.4_

I just noticed that when AxiDraw Control completes a plot, it returns the pen to the home position, but the pen is not in the (full) up position:
If I afterwards manually execute the `Toggle Pen between up/down` command in AxiDraw Control, the pen ends up much higher,  just as it is set in the configuration.

I suspect that after plotting the pen is in the home position somewhere between the up and down positions, but I'm not entirely sure.

Thanks a lot, kind regards,
Thomas

**Comment by schittli** [comment]
I have a small addition:

![image](https://user-images.githubusercontent.com/8282673/148050207-581e4593-53cd-4bb0-b859-9be8b596be26.png)

Thanks a lot, kind regards,
Thomas

**Comment by schittli** [comment]
## Maybe an important note: A single rubber band is in place

In the Manual, you write:
> A single rubber band can be looped loosely around the pen holder as shown, to add a small amount of additional pressure for use with ball-point pens, …

I use this kind of single rubber band to get additional pressure.
And I can perfectly move the Pen up/down using the `Toggle Pen between up/down` command.

Could it be that this single rubber band is the cause of this problem and not a software issue?

**Comment by oskay** [comment]
I am not immediately able to replicate this issue. I've tried with a few different plots of different duration, and different pen-up heights.

It could be that the pen position is slipping, or that the servo motor is at end of life. I would encourage you to precisely calibrate the pen-up and pen-down heights, perhaps against specific stacks of coins and perhaps neither height touching the paper, to see if you're getting a consistent height when the pen returns home.

The streak on the paper does suggest that the pen height isn't being consistent.

Rubber bands will always decrease the life of the servo motor.

**Comment by schittli** [comment]
Thank you very much, @oskay for your support!

I already had precisely calibrated the pen-up and pen-down heights, and watching, as AxiDraw writes, it actually always looked very good how he changed the pen position.
Therefore I just used AxiDraw during the last 9 days without the rubber band and I no longer had the problem with those unwanted lines.
Actually, the rubber band didn't create very much pressure, but maybe it was still too much or maybe the servo motor doesn't have enough power anymore, I'll see how I can replace it. 

I hope it is OK if I close this issue. If someone has the same problem, they can add information 😄 

Thanks a lot, kind regards,
Thomas
