### ISSUE TITLE
Plot Scale is not 100%

### ISSUE THREAD

**Issue by Joe0hara** [evil-mad/axidraw#123]
I exec this code.
But plot scale is not 100%, but about 76%.
How can I plot with the correct size?

thanks,

```python
import os.path
from pyaxidraw import axidraw

svg_text = '<?xml version="1.0" encoding="utf-8" ?><svg baseProfile="full" height="210mm" version="1.1" viewBox="0 0 297 210" width="297mm" xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink"><defs /><path d="M 5,3 L 5,3 204,3 204,144 5,144 5,3" id="test" /></svg>'

ad = axidraw.AxiDraw()
ad.plot_setup(svg_text)

ad.options.units = 2
ad.update()

ad.plot_run()

ad.disconnect()
```

**Comment by oskay** [comment]
Which model of AxiDraw are you using? You haven't set one.

It looks like that should draw a rectangle 199 x 141 mm.  Are you getting a different size? 

The `options.units` have no effect here, and `update()` should *not* be used in the Plot context like this.

**Comment by Joe0hara** [comment]
I use Axidraw v1 A4.
Is this model not supported?
