### ISSUE TITLE
Pen Raise/Lower functions are switched

### ISSUE THREAD

**Issue by samseurynck** [evil-mad/axidraw#124]
Hey!
I've been plotting a bit recently on my new V3 and have had no issues at all (except for with inkscape- that's another thing). 

I got started plotting today and things were off from the start- first the pen I was using shifted at the beginning of the plot so the plot was wobbly and imprecise. When I fixed this and reset to make a new plot, the pen wasn't hitting the paper, so I lowered the pen a bit. Then when I started plotting again, it became clear that the issue wasn't with the pen position, it was with something else, as the pen is in the opposite raised/lowered position then it should be. It's up when it should be drawing a line and down when it should be moving in-between lines.

**Comment by oskay** [comment]
In the Setup tab of AxiDraw Control, you can set the "pen down" position to be higher than the "pen up" position if you need to reverse them.
