### ISSUE TITLE
How to switch between plot and interactive mode?

### ISSUE THREAD

**Issue by clemense** [evil-mad/axidraw#125]
I would like to switch back and forth between plot and interactive mode. Unfortunately, this
```
from pyaxidraw import axidraw 
ad = axidraw.AxiDraw()
ad.interactive()
connected = ad.connect()
if not connected:
    exit()
ad.move(0.2, 0)
ad.plot_setup('blabla.svg')
ad.plot_run()
ad.interactive()
ad.move(0.2, 0)
ad.disconnect()
```
doesn't work and no failure message or exception is thrown. And none of the examples shows this use case.
How can I achieve this?

Thanks!

**Comment by oskay** [comment]
As it says in [the docs](https://axidraw.com/doc/py_api/#connect), you **must** close the connection to the AxiDraw at the end of your interactive context session, using `disconnect()`.

If you do not, then you are entering into undefined behavior, which will not necessarily work nor will it necessarily produce error messages, nor will it necessarily fail gracefully. So, close the Interactive session before starting a Plot session.

You also need to open a new Interactive session before second `move()` command.

As an aside, the ["manual walk" commands](https://axidraw.com/doc/py_api/#walk_x-walk_y) are probably better suited to this application, if the goal is to reposition the carriage -- offsetting it from Home -- before starting subsequent plots and/or moving Home after.
