### ISSUE TITLE
Return non-zero exit code when physical pause button is pressed

### ISSUE THREAD

**Issue by migurski** [evil-mad/axidraw#126]
I sometimes chain plot commands together, like this:

    axicli && axicli && axicli

If during one of those commands I press the physical pause button, `axicli` stops drawing as it should but the zero exit status immediately moves on to the next plot in the chain. A non-zero status would halt the set of commands completely.

**Comment by oskay** [comment]
Interesting. I'll have to think about this.

Right now, non-zero status is only used (I believe) for a couple of error conditions, and a pause is not an error condition. Pauses can happen because they are programmed in the SVG file, from a physical button press, or keyboard interrupt.

**Comment by migurski** [comment]
Physical button presses and keyboard interrupts both seem like exceptional events that could lead to a non-zero exit status. No idea about the SVG pause events!

**Comment by oskay** [comment]
Indeed.

**Comment by oskay** [comment]
Feature implemented as of v3.6.
