### ISSUE TITLE
Axicli progress bar reports 100% complete after resume (3.5.0)

### ISSUE THREAD

**Issue by smkirby** [evil-mad/axidraw#132]
Using res_plot mode and the progress bar leads to axicli reporting that the plot is completed from the start of the resumed plot. (In all other aspects the plot proceeds as expected.)

**Comment by oskay** [comment]
Confirmed that the progress bar is not working correctly in `res_plot` mode.

**Comment by oskay** [comment]
Should be fixed in 3.6.
