### ISSUE TITLE
Resume feature occasionally fails to draw anything.

### ISSUE THREAD

**Issue by smkirby** [evil-mad/axidraw#134]
I have a large plot with many lines and the resume features often fails to restart properly, using the command line interface. After pausing the plotter using the button on the device, and then restarting with the resulting output file, the plotter doesn't draw any more but just returns to home. This happens if res_plot is used immediately or if res_home and then res_plot are chained together. (In the latter case, the plotter moves out to the correct place but then just returns home again.) 

I attach an example resume file where this has happened (I pressed pause shortly after the original file started plotting).
[resume_backup.svg.zip](https://github.com/evil-mad/axidraw/files/9895656/resume_backup.svg.zip)

**Comment by smkirby** [comment]
I just realised that my version of axicli is not up to date (3.5.0). I will update and test with 3.6.0 and close if it works ok!

**Comment by smkirby** [comment]
OK - looks like this problem does not show up so far in 3.6.0 (fingers crossed!)

**Comment by oskay** [comment]
I'm sorry for the trouble, and glad that it's resolved.
