### ISSUE TITLE
Python API: moveto() lowers pen

### ISSUE THREAD

**Issue by martinleopold** [evil-mad/axidraw#137]
Got my new axidraw V3/A3, and want to use it from Python mainly. I tried the interactive mode example from https://axidraw.com/doc/py_api/#quick-start-interactive-xy

```python
from pyaxidraw import axidraw

ad = axidraw.AxiDraw()
ad.interactive()

connected = ad.connect()
if not connected: exit()

ad.moveto(1, 1)               # Pen-up move to (1 inch, 1 inch)
ad.lineto(2, 1)                 # Pen-down move, to (2 inch, 1 inch)
ad.moveto(0, 0)   # Bug: Lowers pen,  draws a line back to the origin

ad.penup()
ad.disconnect()
```

This is what it produces:

https://user-images.githubusercontent.com/1692826/200878254-a93d4e62-110b-4c86-a6d5-cc19a7f08a34.mov

I don't think this is the intended behavior, according to the docs `moveto()` should raise the pen, but the `moveto(0,0 )` in my example does draw a line.

**Comment by oskay** [comment]
Confirmed; thank you.
