### ISSUE TITLE
Potential workaround for Inkscape issue in MacOS

### ISSUE THREAD

**Issue by haschdl** [evil-mad/axidraw#142]
This might be a long shot, as this issue is caused mostly on MacOS and Inkscape. 
Using Inkscape in full-screen mode in MacOS has some usability issues. A quite annoying one is that extension dialogs will also load in full-screen, looking like another tab next to open documents. It looks ugly, but it is also counter-intuitive, and makes navigating from the dialog back to the image very clumsy.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/9550197/210216077-f956960b-7fd6-4692-ac91-a7c605d51949.png">

The full-screen issue is a possible bug in Inkscape https://gitlab.com/inkscape/inkscape/-/issues/4002

@oskay would there be a workaround for the extension dialog to behave like a modal dialog and not go full-screen?

**Comment by oskay** [comment]
There's nothing that an Inkscape extension could do differently when Inkscape resizes *all* of its dialogs this way.  I would recommend never running Inkscape in full-screen mode.

**Comment by haschdl** [comment]
Thank you @oskay ! I have just switched to Rectangle, the new window management tool for MacOS, which comes with "almost fullscreen" shortcut, so that will do for now.

**Comment by oskay** [comment]
Ooo that looks really cool. 👀 

I'm now paying attention this but in Inkscape, and I'll do what I can to help move it towards a resolution. (Appears to be a bug in the GTK3 GUI that Inkscape uses.)
