### ISSUE TITLE
Possible causes for "'AxiDraw Control' working, please wait..." ?

### ISSUE THREAD

**Issue by haschdl** [evil-mad/axidraw#145]
I am regularly facing a long delay after a plot operation completes or is paused. I understand that the dialog "'AxiDraw Control' working, please wait..." is from Inkscape, but what is exactly waiting for, given that the plotter is stopped? 
![image](https://user-images.githubusercontent.com/9550197/220333478-c3acf607-3d53-4ba3-baaa-4314ede2a9d0.png)

* AxiDraw SE/A3
* AxiDraw software 3.8.0

**Comment by oskay** [comment]
When a plot ends for any reason, the AxiDraw software sends the SVG back to Inkscape, and Inkscape parses the file to look for any changes. The processing time that Inkscape takes to do this depends on many factors including the Inkscape version, the number of individual objects, selection status, and so forth.

In my testing here, even for files that take as much as a minute to start plotting, Inkscape generally regains control within several seconds of pressing the pause button.

If you are seeing long delays, you might consider:
* Restarting Inkscape and/or your computer
* Saying which Inkscape and macOS version you are using
* Trying the AxiDraw CLI for plotting
* Saying how long of delays you are seeing
* Providing an SVG file for us to look at

**Comment by haschdl** [comment]
HI @oskay restarting the computer did help! The delays are no longer a problem (tested with the same SVG files).

It is probably not worth investigating it further, feel free to close if you think so. But here's the answers anyway. 
* The delays were in 10s of seconds, sometimes up to a minute. 
* Inkscape is 1.2.1 running on MacOS Venture 13.1
