### ISSUE TITLE
Cannot resolve "Document does not have valid dimensions" error on Ubuntu 14.04

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [evil-mad/axidraw#15]
Hello, I got up and running on my AxiDraw on OS X in under five minutes, which was wonderful!

I'm having a little more trouble getting everything working on Ubuntu 14.04 though:

No matter what document I create or open in Inkscape, or how many times I change "Inkscape Preferences" and "Document Preferences" to use mm or inches, I'm unable to get the AxiDraw extension to begin plotting. (Note, I am able to move the pen up and down via the AxiDraw interface, so I believe serial is getting to the AxiDraw).

Even with a brand-new Inkscape document with the following steps, I see the "not in right units" error message and am unable to remedy it:
- open fresh inkscape install on 14.04
- close install (this is just to create the extensions folder)
- copy the unzipped v102-Full.zip contents into ~/.config/inkscape/extensions/
- open Inkscape
- set Document Preferences to A4 Portrait and make sure units are mm
- draw one rectangle on the document
- Attempt to draw using Extensions > AxiDraw > Apply
- See error "The document does not have valid dimensions"

I'm running Ubuntu 14.04 on a Toshiba Chromebook 2 via crouton.

Notably, I had everything working on the same hardware using Ubuntu 12.04 (or whatever the LTS Ubuntu 12 was called). I only changed over to Ubuntu 14 because I want to use AxiDraw with PaperJS, and Chrome isn't available on Ubuntu 12.

Please let me know if I can provide any more information that would help. Thanks for any assistance anyone can provide, and thanks again for making an excellent plotter!

AKA

**Comment by oskay** [comment]
I'm sorry to hear about the trouble. 

Please try again, but begin with the template, instead. 
Select from the menu File > Templates..., and select the "A4 Page" template.

Does this method behave any differently?

**Comment by AKAMEDIASYSTEM** [comment]
Thank you for the quick reply!

Going to "File > New > A4" (I could not find a "Templates" option), then drawing a rectangle, then trying to plot does indeed result in different behavior: the plotter (which was manually set in home position before any connections or power were applied) moves down to the extreme bottom of the page, makes one dot, and then concludes plotting. An Inkscape message appears, warning me that "AxiDraw movement was limited to its physical range".

...even if I make the test rectangle _super_ teeny, the plotter still does the above behavior, heading to the extreme of one axis, making a dot, then concluding.

I tried several other templates, since it seems like the error we're encountering is an Inkscape init thing and not necessarily an AxiDraw thing. Some templates (A4, Letter) result in this behavior, and others (default_mm) return the initial "valid dimensions" error.

I know you're just getting back from the East Coast, and I'm happy to use OS X with my AxiDraw, so to me this is a low-priority issue - please don't take my quick replies for impatience ;-)

Thanks again for your help!

AKA

**Comment by oskay** [comment]
I'm not yet sure what is causing this. It could be a difference between the templates on the different versions, but I suspect that it's something deeper.
- Can you please check what Inkscape version number you are seeing on Ubuntu?
- Do you get the same units error if you try to open one of our example files?

**Comment by AKAMEDIASYSTEM** [comment]
Oh my, I was running Inkscape 0.48. **I am so sorry** I did not double-check that before opening this issue!

That said, it took a bit of fiddling to go from fresh Ubuntu 14.04 on a Chromebook to successful plotting, so here are my notes in case they might assist anyone else:
- run `sudo apt-get install software-properties-common` in order to get the `add-apt-repository` command
- run `sudo add-apt-repository ppa:inkscape.dev/stable`
- run `sudo apt-get install inkscape`

...this gets you Inkscape 0.91 (I had to clobber my old 0.48 install before trying all this, as even after updating the repos, running `sudo apt-get install inkscape --upgrade` did not work).

However, at this state I still frequently encounter the "Units not in valid dimensions" error message if I compose from the default new doc created up on inkscape opening, so I always immediately open the A4 template suggested by @oskay and just paste my work in to there.

Thanks again for the very fast and effective help - I'm so glad I've got a whole chromebook dedicated to my AxiDraw now!

AKA

**Comment by oskay** [comment]
OK; great-- I'm glad that this has an explanation!

Thank you so much for following up and including instructions about how to update Inkscape. That will surely help someone else when they run into this same issue.

We do have it on our agenda to try and resolve the issue with setting dimensions via the document preferences (#5), and hope to include that in our next release.
