### ISSUE TITLE
Ошибка can't open file 'eggbot_hatch.py'

### ISSUE THREAD

**Issue by Gogasan04** [evil-mad/axidraw#150]
Здравствуйте. Inkscape выдаёт ошибку при создания штриховки.
Inkscape получил дополнительные данные от выполненного сценария. Сценарий не возвратил ошибки, но это может означать и то, что результаты будут отличаться от ожидаемых.
C:\Program Files\Inkscape\pythonw.exe: can't open file 'eggbot_hatch.py': [Errno 2] No such file or directory
Пытался несколько раз переустановить, не помогло. Все файлы есть и скачены. Может их надо куда-то перенести?
Подскажите, пожалуйста, как исправить.

**Comment by oskay** [comment]
The error indicates that you do not have all of the software installed correctly. I suggest that you install a fresh copy, following the instructions at: https://wiki.evilmadscientist.com/Axidraw_Software_Installation

**Comment by Gogasan04** [comment]
Спасибо. У меня стояла версия 0.94.2. После обновления до 1.2 всё заработало. Спасибо
