### ISSUE TITLE
Newest setuptools (from v69.0.0) breaks package

### ISSUE THREAD

**Issue by dr-emp** [evil-mad/axidraw#167]
Doing

`from pyaxidraw import axidraw`

results in

`E ModuleNotFoundError: No module named 'axidrawinternal'`

## Background:

`pip install https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip -v`
 
shows that 

```
/tmp/pip-build-env-6y8yden2/overlay/local/lib/python3.11/dist-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `dependencies` defined outside of `pyproject.toml` is ignored.
  !!

          ********************************************************************************
          The following seems to be defined outside of `pyproject.toml`:

          `dependencies = ['ink_extensions>=1.3.2', 'lxml>=4.9.1', 'plotink>=1.8.0', 'pyserial>=3.5', 'requests', 'axidrawinternal@ file:///tmp/pip-req-build-zy558yn5/prebuilt_dependencies/axidrawinternal-3.9.4-py2.py3-none-any.whl']`

          According to the spec (see the link below), however, setuptools CANNOT
          consider this value unless `dependencies` is listed as `dynamic`.

          https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

          To prevent this problem, you can list `dependencies` under `dynamic` or alternatively
          remove the `[project]` table from your file and rely entirely on other means of
          configuration.
          ********************************************************************************

  !! 
```

It appears that "setuptools" was updated on 20th of November with a breaking change. From the [changelog](https://setuptools.pypa.io/en/latest/history.html#deprecations-and-removals) of setuptools v.69.0.0, one can see the following:

`Added strict enforcement for project.dynamic in pyproject.toml. This removes the transitional ability of users configuring certain parameters via setup.py without making the necessary changes to pyproject.toml (as mandated by PEP 621). (#4066)`

It seems that this project still uses setup.py for configuring dynamic dependencies, which leads to the the issue above. Axi draw project specify, in the pyproject.toml file of the axi draw project the following:

```
[build-system]
requires = ["setuptools >= 40.6.0"]
build-backend = "setuptools.build_meta"
```

This means that pip will use the latest setuptools, with this breaking change. 

## Proposal for solutions:

Quickfix: You can fix (enforce) setuptools version to something less than v69.0.0.

Alternatively, you have to update pyproject.toml (with related setup.py) so that it adheres to PEP 621.

**Comment by oskay** [comment]
Thanks; we'll take a look.

**Comment by xanderjl** [comment]
Came to report the same issue. While not pulling in the module for a custom script, calling the `axicli` command fails.
`zsh: command not found: axicli`. When I try to call it with `python3 -m axicli`, I get a similar output:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/xander/.pyenv/versions/3.12.0/lib/python3.12/site-packages/axicli/__main__.py", line 1, in <module>
    from .axidraw_cli import axidraw_CLI
  File "/home/xander/.pyenv/versions/3.12.0/lib/python3.12/site-packages/axicli/axidraw_cli.py", line 66, in <module>
    from pyaxidraw.axidraw_options import common_options
  File "/home/xander/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pyaxidraw/__init__.py", line 53, in <module>
    main()
  File "/home/xander/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pyaxidraw/__init__.py", line 40, in main
    raise ie
  File "/home/xander/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pyaxidraw/__init__.py", line 34, in main
    sys.modules[__name__].__dict__[name] = alias_submodule(supermodule_name, name)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xander/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pyaxidraw/__init__.py", line 49, in alias_submodule
    __import__(full_name)
ModuleNotFoundError: No module named 'axidrawinternal'
```

Using python 3.12.0 via pyenv.

**Comment by oskay** [comment]
I'm wrapping up a different project but hope to get a chance to look at this in the coming week. One person reports that they were able to get it to install by first using `pip install prebuilt_dependencies/*`, in the unzipped download.

**Comment by xanderjl** [comment]
Oh interesting! I'll give that a shot. Thanks @oskay

**Comment by dr-emp** [comment]
Some tips for when you start looking into it @oskay:

If you add
`requires = ["setuptools >= 40.6.0, <69.0.0"]`
instead of 
`requires = ["setuptools >= 40.6.0"]`

in cli/pyproject.toml (line 48), I think the issue should be resolved _for the current package setup with setup.py_ for dynamic dependencies (this solution forces "setuptools" to be less than the breaking "setuptools" version I mentioned above, which ignore dynamic dependencies in setup.py). I have tested this by doing:

`wget https://cdn.evilmadscientist.com/dl/ad/public/AxiDraw_API.zip`

and then adding 

`requires = ["setuptools >= 40.6.0, <69.0.0"]`

inside the downloaded cli/pyrpject.toml, and can verify that we get a successful install (upon doing "pip install ."). 

 I can both do:

`from pyaxidraw import axidraw`
and
`python3 -m axicli`

successfully.

**Comment by xanderjl** [comment]
> I'm wrapping up a different project but hope to get a chance to look at this in the coming week. One person reports that they were able to get it to install by first using `pip install prebuilt_dependencies/*`, in the unzipped download.

Just wanted to report that this method worked.

- cd into API dir
- `pip install prebuilt_dependencies/*`
- `pip install .`
- I opted to add `alias axicli="python -m axicli"` to my `.zshrc` file on my rpi4. zsh complained that the axicli command was not found otherwise.

**Comment by oskay** [comment]
We're pushing a minor update (v 3.9.5) to cover this (along with a few other bug fixes).

Here's the package ahead of formal release: 
`python -m pip install https://cdn.evilmadscientist.com/dl/ad/public/395/AxiDraw_API_395.zip`

**Comment by dr-emp** [comment]
Great, thank you!
