### ISSUE TITLE
Distutils removed in Python 3.12

### ISSUE THREAD

**Issue by snow6oy** [evil-mad/axidraw#173]
The Axidraw Inkscape driver stopped working after I upgraded to Ubuntu 24. I think the root cause is distutils as mentioned.

https://gitlab.com/inkscape/extensions/-/issues/432

Migrating to setuptools seems to be the common remedy. I saw this commented in the code here, but also see references to distutils. Can you confirm if this is a known issue and whether there are any plans to completely remove distutils in a future version.

Thanks
Gavin

**Comment by oskay** [comment]
Can you please post the exact error message that you're getting? And, please report which exact version you're running.

I don't see anything else mentioned about distutils and the AxiDraw extension for Inkscape; can you please say what it is that you're referring to?

**Comment by snow6oy** [comment]
![Screenshot from 2024-10-03 14-14-15](https://github.com/user-attachments/assets/fdf758a7-b45c-4dc5-abd5-a7a017d1ef2e)

Its a bit easier to read from the command line
```
$ cd ~/.config/inkscape/extensions/axidraw_deps
$ python3 -m urllib3.packages.six.moves
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/gavin/.config/inkscape/extensions/axidraw_deps/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/gavin/.config/inkscape/extensions/axidraw_deps/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/gavin/.config/inkscape/extensions/axidraw_deps/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```
The version is unknown but the source is a zipfile distributed via Google Drive by Uunatek. 

https://uunatek.com/pages/downloads

The theory that distutils is the culprit comes from [PEP 632](https://peps.python.org/pep-0632/) and Ubuntu 24 shipping with Python 3.12. But it's just a theory .. I have also asked Uunatek support.

Thanks

**Comment by oskay** [comment]
We definitely cannot support a fork from uunatek -- if you can reproduce the issue in our software, please feel free to open a new issue for it.
