### ISSUE TITLE
AxiDrawAPI requirements

### ISSUE THREAD

**Issue by letsgocodego** [evil-mad/axidraw#175]
So, I know Evil Mad Scientist was bought out or whatnot but the requirements.txt for the AxiDrawAPI has the following line:

axidrawinternal @ git+https://${AXIDRAWINTERNAL_DEPLOY_USER}:${AXIDRAWINTERNAL_DEPLOY_PASS}@gitlab.com/evil-mad/AxiDraw-Internal@master

And as far as I can tell, this repository no longer exists. Thus, it is impossible for me to import pyaxidraw.... *sigh*

**Comment by oskay** [comment]
Installing via the requirements file has never been supported; please follow the installation instructions instead.
