### ISSUE TITLE
Axidraw is not recognized (anymore) on latest macOS and Raspbian

### ISSUE THREAD

**Issue by stphnthiel** [evil-mad/axidraw#31]
I am having the following issue with an Axidraw v3:

It driver/software does not seem to work on macOS 10.12.4. Is this known to be a problem? We've tested two different MBPro models with, no luck. Another MBP with 10.12.3 works.

After having successfully used the same machine from a RaspberryPi with newest Raspbian running cncserver, it now has stopped to work as well. 

Is there a way to reset/force update the firmware to ensure the Axidraw works as expected and to narrow down the problem? Is there any other way to diagnose the state of the board/software?

Thanks for your help!

**Comment by oskay** [comment]
We don't use Raspbian, so I can't comment on that. However, there is not any known issue or widespread case of AxiDraw failing on MacOS. Our primary development and test machines are macs, some on 10.12.4, and we have not had any other reports that sound similar. That is also not a matter of firmware.

It sounds like there is an issue with your particular machine (or with your USB cable) -- please contact technical support directly.
