### ISSUE TITLE
Create a high speed, low precision mode where the pen never stops

### ISSUE THREAD

**Issue by Daekkyn** [evil-mad/axidraw#33]
In order to reduce plotting time, it could be possible to not stop the pen during pen up/pen down transitions. It will be hard to have the same precision as normal because the weight and height of the pen are not known. But by having the user tweak a parameter it should be possible to get decent results. 
This would be particularly interesting for stippling patterns with many dots or for dashed lines.

**Comment by oskay** [comment]
I'm not fully sure that I understand what you are suggesting.  Can you please clarify what exactly would change, and how you would control it?

**Comment by Daekkyn** [comment]
Imagine a drawing with a single line. Currently when you start the plotting, the pen moves to the start of the line, stops, lowers the pen, moves along the path, stops at the end, raises the pen and goes back to the origin. My suggestion is to have a mode that doesn't stop the pen during lowering and raising of the pen. It would move smoothly from the start of the drawing till the end without stoping.
I think this might not require much changes in the code, mainly, the pen should not decelerate at the end of a path.

**Comment by Daekkyn** [comment]
Actually, it might not be possible with the EBB firmware to move the pen up/down servo at the same time as the motors :(

**Comment by oskay** [comment]
Many things are possible, _including changes to the firmware_, but we need to understand and evaluate the feature request first, and see how it might fit into things.

It sounds like you are chiefly concerned about the slowing down at the beginning and end of paths? If so, just turn on the constant speed option-- it disables the pen-down acceleration.

The delays when lifting and lower the pen are chiefly to ensure that the pen is fully up or fully down before moving, and that it has moved to the final location before the pen lifts. These are significant quality issues, that are amongst the most common that our users run into. 

The delay time is calculated as ((high position - low position) / rate). So, to make vertical movements faster (at the cost of that type of precision), make sure that the pen-up and pen-down heights are no higher/lower than they need to be. (And, if you set them to the same height, there shouldn't even be a delay there.)  Then, pick as high of a rate as allowed for lifting and lowering. You can pick up to 500 for each, and while the motor may not keep up, it will make the horizontal performance faster.

**Comment by oskay** [comment]
I am closing this for the time being, as it does not seem like more information is forthcoming. Please feel free to add additional comments if this needs to be re-opened.
