### ISSUE TITLE
Use multiple AxiDraw machine at one

### ISSUE THREAD

**Issue by clifflo** [evil-mad/axidraw#36]
Hi due to quite a lot of svg to print I would like to purchase may be three to four AxiDraw and then run them at once. How can I control multiple AxiDraw at once?

**Comment by oskay** [comment]
We do not currently have support for a feature like that, but it is an occasional request, and it is worth thinking about. (It is also worth noting that in the era of $200 laptops and $5 Raspberry Pi, it is often the cheapest and most straightforward solution to _just use another computer_.)

Would you be attempting to plot the same thing on all of the machines, or different things?

**Comment by oskay** [comment]
We have a first version of this working, which can drive multiple AxiDraw units to plot the same file simultaneously, launched from the command line (a variant of #9). 

If any AxiDraw users would like to try it out, it's a little rough around the edges, but may eventually make a nice feature. We'll make development versions available in private beta for AxiDraw users. Please contact us directly (e-mail or contact form) and we can follow up.

**Comment by oskay** [comment]
Support added from Inkscape as well, at least for naming AxiDraw units and plotting to them individually:  https://github.com/evil-mad/axidraw/issues/39
Will leave this open for simultaneous plotting of the same file to multiple machines.

**Comment by oskay** [comment]
All cases supported as of current version on 2.x branch.

**Comment by ProvanceMedia** [comment]
Hi,

I am looking for a way to plot to several Axidraw's at once. Is this now available?

Thanks

**Comment by oskay** [comment]
Yes; plotting the same document to multiple AxiDraw machines is supported from the GUI, and the CLI supports plotting individual documents to individual AxiDraw units.
