### ISSUE TITLE
Bug: Beta driver manual control problems

### ISSUE THREAD

**Issue by MartyMacGyver** [evil-mad/axidraw#42]
Setup:

- AxiDraw V3
- Windows 7 x64
- Python 3.6.3 is my default Python
- Inkscape 0.92.2 (5c3e80d, 2017-08-06)
- AxiDraw v1.5.9-beta (overwriting original AxiDraw v1.2.2 driver files)
  - pySerial was unchanged from what v1.2.2 installed.

Problem:

Using Inkscape, the AxiDraw manual mode commands to raise / lower the pen failed to work. I haven't tried other commands exhaustively. Overwriting the 1.5.9 driver files with the contents of the original v1.2.2 driver restored normal functionality.

**Comment by oskay** [comment]
I'm not in front of my AxiDraw to test right now, but I would suggest that you try instead from the setup tab, to see if that works for you.

(Also, for reasons, Inkscape 0.92 is _not_ officially supported-- we are still recommending 0.91, but will likely be migrating to 0.92 support as of our next stable release.)

**Comment by MartyMacGyver** [comment]
Interesting - Inkscape 0.92 seems to work quite well with the 1.2.2 driver. As 1.5.9 is on the road to stable it's probably a good thing I found this.

At this point I'm curious to see if you have the same issue (it's not urgent but it is worth tracking it).

**Comment by oskay** [comment]
Just to be aware: One of the big changes with 0.92 is a change in the number of pixels per inch -- changing from a historical 90 PPI to 96 PPI, as adopted in the SVG standard. While some things will work, you may also find some things come out at the wrong size.

**Comment by oskay** [comment]
The issue turned out to be a mis-implementation of a function in the plotink libraries. I've re-packaged the download -- including the fixed file -- as v159r2_noserial.zip: 

https://github.com/evil-mad/axidraw/releases/tag/v1.5.9-beta

**Comment by MartyMacGyver** [comment]
Things have been busy but I will check this out - thanks for looking into it!
