### ISSUE TITLE
 About“paused” need help

### ISSUE THREAD

**Issue by niudvb** [evil-mad/axidraw#43]
Excuse me, when I started drawing, once every operation, the Inkscape tip: “Plot paused by button press after node number 0.Use the "resume" feature to continue.” It didn't actually press the PRG button.

After running the serial command "SC,13,0\r", inkscape can be used normally. But restart after Shut Down , the problem arose.

 Please help, Thanks!

system : windows7 64bit
inkscape : 0.91 64bit
EBB : v2.3 white
Firmware Version: 2.5.1
Axidraw control: Every version takes place

**Comment by oskay** [comment]
Which version of the AxiDraw software are you using?

**Comment by oskay** [comment]
Looks like you edited to say “every version”

**Comment by oskay** [comment]
Is the pause button physically able to move; does it click up and down? Does the pause button work correctly otherwise?

**Comment by niudvb** [comment]
Pause button work ok.

**Comment by niudvb** [comment]
When  the AxiDraw software runs normally, it can be paused by the pause button.

**Comment by niudvb** [comment]
Before each normal use, must run:SC,13,0\r

**Comment by oskay** [comment]
If you reset the EBB does that command still need to be run to get normal operation?

**Comment by niudvb** [comment]
Yes

**Comment by oskay** [comment]
I'd suggest updating to the current firmware 2.5.3, just to see if that makes any difference.

**Comment by niudvb** [comment]
Is this a hardware problem？

**Comment by niudvb** [comment]
After the upgrade 2.5.3, the same question was asked. “Plot paused by button press after node number 0.”

**Comment by EmbeddedMan** [comment]
Do you have anything connected to the RB0 input pin?

*Brian

**Comment by niudvb** [comment]
RB0 is empty.

**Comment by EmbeddedMan** [comment]
Can you send the command "PI,B,0" and reply with what the EBB sends back?
This will tell us if the alternate pause button input pin (RB0) is stuck
low or not.  (If nothing is connected to it, it should be high, so you
should get back "PI,1")

*Brian

**Comment by niudvb** [comment]
When I first had a problem, I checked 'ebb.html' and knew that RB0 was  alternate pause button , so I tried it through the SC command, after running  "SC,13,0\r", inkscape can be used normally. But restart after Shut Down , the problem arose.

**Comment by niudvb** [comment]
I send the command "PI,B,0"  and get back "PI,0".

**Comment by niudvb** [comment]
I think I ran into a hardware problem.

**Comment by niudvb** [comment]
I need to check the motherboard carefully. Thank you  EmbeddedMan and oskay !

**Comment by oskay** [comment]
OK, closing this for now. (Hardware, not software.) If the issue appears to be software related after all, please feel free to reopen.
