### ISSUE TITLE
Feature Request: Hatch fill individual SVG groups

### ISSUE THREAD

**Issue by DBraun** [evil-mad/axidraw#44]
My SVG is a bunch of sibling <polygon> tags. Is it possible to use the hatch fill extension to fill each polygon individually but not make connections between polygons? I think I'm just using the settings incorrectly.
[hatch_fill_svg.zip](https://github.com/evil-mad/axidraw/files/1469437/hatch_fill_svg.zip)

Edit: I'm moving this issue to EggBot https://github.com/evil-mad/EggBot/issues/90

**Comment by oskay** [comment]
Hatch Fill does not work well on sets of vanishingly thin objects. This is a known issue, and one that could definitely use improvement.

I was able to get your file to work with the following settings:

Spacing 2.0
Angle: 45
Connect: Yes
Range: 3.0
Inset: Yes
Inset by 0.5
Tolerance: 1.0  

I was also able to get the individual slices to work (on a wider variety of settings) by ungrouping and selecting them individually.
