### ISSUE TITLE
cant use my axidraw. error to do with python?

### ISSUE THREAD

**Issue by danny5497** [evil-mad/axidraw#45]
I keep getting this and have no idea what to do.

The fantastic lxml wrapper for libxml2 is required by inkex.py and therefore this extension. Please download and install the latest version from http://cheeseshop.python.org/pypi/lxml/, or install it through your package manager by a command like: sudo apt-get install python-lxml

Technical details:
No module named lxml

**Comment by oskay** [comment]
That appears to be an error within Inkscape, where none of the extensions are working because of a system configuration error. (If you try other extensions, for example Extensions > Render > Gear, you'll get the same error.)

Which Inkscape version are you using, and which operating system version are you using?

**Comment by danny5497** [comment]
Pim using Windows 10 and inkspace 0.91

**Comment by oskay** [comment]
I'm not sure what PIM is, in this context.

Try uninstalling (not just deleting, but uninstalling) Inkscape, and re-installing it. (You can uninstall a program in Windows 10 by right clicking on it in the Start menu and selecting Uninstall.)

If that doesn't work, you probably have an old "PYTHONPATH" variable set in your system. 
Open up Control Panel, and type `path` in the search box there. Click on "Edit environment variables for your account" to get to a list of your environment variables.  Then, locate the PYTHONPATH variable and remove it. If you are concerned that this variable may currently be in use elsewhere, you might want to copy the value of it and save that (e.g., with notepad) before deleting it.

**Comment by danny5497** [comment]
Thank you so much for the help. I shall give it a go. Pim was a spelling mistake lol.

Again thank you for your help.

**Comment by oskay** [comment]
I'm going to mark this resolved for the time being. If the issue persists, please feel free to open it again.
