### ISSUE TITLE
Readme update: latest PySerial seems to work fine in Windows

### ISSUE THREAD

**Issue by MartyMacGyver** [evil-mad/axidraw#50]
There's a warning in the Readme that I just noticed:

    Pyserial. (Note that an older version, 2.7, must be used on Windows.)

I've been using the latest version of PySerial on Windows since I got my AxiDraw and it works fine.

If this warning is still required, some verbiage about what version of Python this affects would be useful. Otherwise the warning may be obsolete.

**Comment by oskay** [comment]
The current version of pyserial requires python 2.7. Unfortunately, the version of python included with Inkscape 0.91 on Windows is 2.6, which does require that we use the older version of pyserial. Once we finish migrating to support Inkscape 0.92 (only), we'll update to the latest pyserial.  

We've been using latest pyserial (in other contexts) for some time on Windows, with good success. (Amongst other things, the CLI version of AxiDraw for Windows does already include pyserial 3.0.)

**Comment by MartyMacGyver** [comment]
I was wondering what Python they baked in. That in 0.91 it's Python 2.6 - which went EOL over 4 years ago - is both surprising and a little alarming. I see some discussion about this on Launchpad... it seems the x64 version of 0.91 has 2.7 now, but it's not clear if the win32 version does:

https://bugs.launchpad.net/inkscape-devlibs/+bug/1575790

Either way, it'd be good to note that this only applies to users of older versions of Inkscape - no need for users of the current 0.92 version or later to deprecate their Python installations or libraries.

**Comment by oskay** [comment]
There are still some showstopper bugs in Inkscape 0.92, which mean that I can't recommend people use it.

**Comment by MartyMacGyver** [comment]
Might be good to mention what those bugs are somewhere in the Readme, if they are actually showstoppers that have no workarounds.

**Comment by oskay** [comment]
Workaround is to use 0.91. :(

**Comment by MartyMacGyver** [comment]
Ok, but what are the actual "showstopping" bugs that I'm not yet encountering? I know they moved to a more standard DPI setting but that was pre-0.91.

**Comment by oskay** [comment]
At present, I'm not able to type text with a reasonable linespacing on a Mac, nor edit text in files. Works fine on Windows....

We've also seen _lots_ of cases of people encountering misconfiguration bugs with the pythonhome path on windows.

The DPI change was between 0.91 and 0.92 as well.

**Comment by MartyMacGyver** [comment]
Ah, I see. http://wiki.inkscape.org/wiki/index.php/Units_In_Inkscape speaks of it being pre-0.91 but elsewhere it mentions 0.91 as well.

Linespacing - is it one of these bugs?

https://bugs.launchpad.net/inkscape/+bug/1652340

https://bugs.launchpad.net/inkscape/+bug/1655483

It seems like it's the reduction of bugs in 0.92 that's causing issues for legacy users (following standards where previously they were not followed as closely, or where standards weren't firmed up).

As for `PYTHONHOME`, it appears to be a source of general pain when set in one's environment. It's not clear to me why anyone would use it normally.

**Comment by oskay** [comment]
Yes, I'm quite aware of those, and no it's not one of them. It's about the behavior even with a new document. There seem to be additional issues (yes, still) with imported documents.

**Comment by MartyMacGyver** [comment]
Then it'd be good to note the major issues with the latest Inkscape 0.92 in the Readme by their bug number (and if there's not a bug report against Inkscape for a given issue that is causing problems here, there ought to be). Otherwise it becomes anecdotal, and things like that have a tendency never to get fixed or worked around (it also encourages the bad habit of staying on old versions "just because").

**Comment by oskay** [comment]
I do report bugs on launchpad, and there is some pressure on us to update to support 0.92. 

Larger than any one bug, _we_ need to be comfortable supporting the new version, and to have reasonable confidence that shifting all of our support docs (across our various machines and platforms) to 0.92 is not going to cause a catastrophe in terms of machines not working as expected. 

This is not a minor concern; if 1 in 100 computers does not work with the new version, we have a real problem. We are not planning to stay behind for long, nor are we leaping at it. 0.92 has been available across platforms since August, and we have anecdotal evidence that things work just fine on it, with one substitution for the DPI change. We'll hopefully be moving beta versions of AxiDraw software to _require_ 0.92 shortly, which should help to identify how widespread the issues really are.

**Comment by MartyMacGyver** [comment]
One in 100 computers - perhaps several in 100 - may never work with modern software, which means some users will simply stay on EOL software versions indefinitely.  My point is that any blocking bugs for the current released version and the in-development version should be tracked somewhere visibly. In addition to being tracked, it'd give users something to check before reporting duplicate bugs (or a place to find workarounds that don't necessarily involve deprecating to EOL versions).
