### ISSUE TITLE
Extension versioning means preferences do not migrate to new releases

### ISSUE THREAD

**Issue by MartyMacGyver** [evil-mad/axidraw#52]
I notice that the extensions have version numbers directly in the `id` tags (e.g., `command.evilmadscientist.axidraw.rev170`. The effect is that each new version of the extensions has its own set of potentially unique option settings, and fails to inherit settings from the previous version. Each upgrade necessitates re-entering settings that ought to have carried forward, while a downgrade would lead to old settings coming to the fore. This behavior is inconsistent with the typical expectation that relevant settings are preserved (or in a more complex system, preservable) on upgrade.

Recommendation: remove revision numbers from the `id` tag for the AxiDraw-related extensions.

**Comment by oskay** [comment]
We started adding the versioning many years ago after some unexpected behavior encountered when altering the number of parameters. However, I cannot seem reproduce that behavior now, so it appears that whatever issues were there have been resolved. 

So yes; good call.
