### ISSUE TITLE
Setting the home position option?

### ISSUE THREAD

**Issue by patakk** [evil-mad/axidraw#54]
I've been using AxiDraw for a short time, but a feature came to my mind regarding home position. 
Sometimes it seems like it would be more convenient if the pen's starting position would correspond to a particular point on the drawing, rather than the top-left corner of the Inkscape's document area.

For example, if you wanted to draw a star on a flat object that has a surface that is not rectangular (or has mushy edges), it is difficult to pinpoint the exact location the pen should be place to match the Inkscape's home position correctly. In this case it would be more convenient to just place an anchor on the drawing area in Inkscape (maybe the star's middle), place the pen above the point on the surface where we want the star's middle to be and start plotting.

I've tried achieving this by placing the carriage at the wanted position and placing my drawing (the star's middle) onto the top-left corner in the document, hoping that AxiDraw would then draw the star exactly where I wanted. Unfortunately, the AxiDraw couldn't draw parts of the star that were outside the drawing area..

Anyway, I hope I explained the idea clearly!

**Comment by oskay** [comment]
I'm afraid that I don't follow the use case that you're trying to explain. It doesn't sound like trying to determine the center of that star would be any easier than setting the home position correctly.

If you need to move the carriage to a particular position and then start there, you could use the existing layer control mechanisms: Draw a dot (on the first layer), then have a pause layer, at which point you insert the pen before continuing.

**Comment by patakk** [comment]
That's a nice workaround, thanks!

**Comment by patakk** [comment]
Got a notification about this being mentioned, and reread the replies.

> It doesn't sound like trying to determine the center of that star would be any easier than setting the home position correctly.


Is that necessarily true? It is a one click command to put an object to another object's center (like that dot in your proposed solution, which works great btw). Setting the home position on an irregular shape sounds like a bit more work honestly.

**Comment by oskay** [comment]
> Is that necessarily true?

The easiest way to determine the "center" of something depends on whether you mean on a drawing of the object, on the physical object, what you mean by "center", and how precisely you need the digital and physical matches to be.  So, everything depends on the particular circumstance.

As far as whether something "doesn't sound easier", I think that's the sort of thing that can or should be pinned down to a "necessarily true" or not. It's just an opinion, of course.
