### ISSUE TITLE
0.92 compatibility and sizing problem

### ISSUE THREAD

**Issue by JelmerT** [evil-mad/axidraw#63]
As I understand the problem for the scaling error in 0.92 has been found (#34 ), but I'm still getting prints at the wrong size in 0.92

Which issues are still open in order to support 0.92? Or what configs need to be changed to get sizing right? (and why aren't they included yet)

**Comment by oskay** [comment]
The current packaged builds (1.7.8) are specific to 0.91. The version currently in final testing (2.2.0) is specific to Inkscape 0.92.

There are changes in how text and page scaling are handled between the two versions. We *think*  that all of the compatibility issues are solved now, but are holding off until we have more real-world confirmation that things are working correctly.

If you'd like to patch 1.7.8, open plot_utils.py, and edit the resolution from 90 to 96.

If you're an AxiDraw owner and would like to help us test 2.2.0 prior to release, please use our [contact form](https://shop.evilmadscientist.com/contact) and we'll send you a download link.
