### ISSUE TITLE
V3/A3 Reaching Reduced Page Limit

### ISSUE THREAD

**Issue by GabiSchaffzin** [evil-mad/axidraw#66]
I scoured the docs and issues, but have yet to see this come up.

I am using a V3/A3 with an extremely simple SVG (I stripped it down for the purposes of debugging). I keep running into a limit of 1133px x 823px.

If a shape is positioned outside that limit, neither the CLI nor the InkScape extension will run. Instead, nothing happens and this warning is given:

`Warning: AxiDraw movement was limited by its physical range of motion. If everything looks right, your document may have an error with its units or scaling. Contact technical support for help.`

If there are objects positioned via x/y within those limits, they will draw, but be cut off at the end of 1133px wide and 823px high. 

I have made sure there are no physical obstructions.

I can run the pen well beyond these limits via the CLI's manual mode:

```
python axicli.py drawing.svg -m manual -M walk_x --walk_dist -17
python axicli.py drawing.svg -m manual -M walk_y --walk_dist -17
```

My SVG looks like this.

This runs but cuts off the rect:

```
<svg width="1530" height="990" viewbox="0 0 1530 990">
  <rect
     y="823"
     x="1133"
     height="50"
     width="50"/>
</svg>
```

This does not run at all:

```
<svg width="1530" height="990" viewbox="0 0 1530 990">
  <rect
     y="824"
     x="1134"
     height="50"
     width="50"/>
</svg>
```

This will run without any warning:

```
<svg width="1530" height="990" viewbox="0 0 1530 990">
  <rect
     y="100"
     x="100"
     height="50"
     width="50"/>
</svg>
```

Any ideas what's going on here? I'm trying to draw on either A3 or 11x17 sheets.

**Comment by oskay** [comment]
Questions:
(1) What version are you running?
(2) Do you have the model set correctly in axidraw_conf.py?

Notes:
(1) Per [documentation](https://axidraw.com/doc/cli_api/#walk_dist), manual walks are _not_ checked against limits. 
(2) You might try explicitly calling `-L2` in your CLI argument.

**Comment by GabiSchaffzin** [comment]
Thank you and apologies for it being something so simple. 

I changed the conf as well as the Version in the AxiDraw Control in Inkscape and both work fine now.

**Comment by oskay** [comment]
Great-- Always glad when it's something straightforward. :)
