### ISSUE TITLE
Parse errors in "inkscape --verb-list"

### ISSUE THREAD

**Issue by EmbeddedMan** [evil-mad/axidraw#68]
Not sure how important this is, as there's probably barely anybody who uses Inkscape command line, and fewer still that would use the --verb-list. But just FYI : with the v2.5.3 AxiDraw software installed, the following parse errors are generated with the shell command "inkscape --verb-list" (This is on Windows 10). It looks like they're related to the hershey font.

org.inkscape.qrcode.noprefs: QR Code (No prC:\Program Files\Inkscape\share\extensions\hershey.inx:59: parser error : Attribute indent redefined
aram indent="0" name="otherfont" type="string" indent="2" _gui-text="Name/Path:"
                                                                               ^
C:\Program Files\Inkscape\share\extensions\hershey_axidraw.inx:59: parser error : Attribute indent redefined
aram indent="0" name="otherfont" type="string" indent="2" _gui-text="Name/Path:"
                                                                               ^
C:\Program Files\Inkscape\share\extensions\hershey_eggbot.inx:59: parser error : Attribute indent redefined
aram indent="0" name="otherfont" type="string" indent="2" _gui-text="Name/Path:"
                                                                               ^
eferences)

**Comment by EmbeddedMan** [comment]
Oh, and this is with Inkscape v0.92.4

**Comment by oskay** [comment]
It was already fixed in hershey.inx, but I forgot about the other two.
