### ISSUE TITLE
how to install SVG Animation Assistant?

### ISSUE THREAD

**Issue by barbn** [evil-mad/axidraw#69]
I downloaded the "SVG Animation Assistant" from { https://github.com/chr15m/svg-animation-assistant } , and i don't know how to install it into Inkscape... (and then were to found it in the program)

i'm very new to Inkscape, so "short" instructions please.

Thanks in advance!

**Comment by oskay** [comment]
Please ask the author of that software. We have not used that software, and don't know what's involved.

**Comment by barbn** [comment]
Do you know where i can ask the author?...
Btw, do you don't have any experience with installing extensions in inkscape?
Thanks anyway...

**Comment by oskay** [comment]
You placed a link to the software here; follow that link.
