### ISSUE TITLE
"axicli version" command doesn't work.

### ISSUE THREAD

**Issue by patakk** [evil-mad/axidraw#72]
The script (`.../cli/axicli/core.py`) tries to import axidraw module from axicli, which it can not and fails. So in order to fix that I changed the 224th line of that script from `from axicli import axidraw` to `from pyaxidraw import axidraw` and now it works fine.  
This is not a big issue, just a bit annoying so I figured I might share it with you.

**Comment by oskay** [comment]
Confirmed in release version.

**Comment by oskay** [comment]
Fixed upstream, will be patched in next release version (2.6.0).

**Comment by oskay** [comment]
Fixed in current release.
