### ISSUE TITLE
Issue with Inkscape V1

### ISSUE THREAD

**Issue by zoso95** [evil-mad/axidraw#74]
I know V1 isn't supported yet, but I just tried adding the extension in directly and this might be useful to know. When I try to toggle on the motors from the menu

axidraw_control.py:44: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from . import axidraw
axidraw_control.py:62: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option_group(
Traceback (most recent call last):
  File "axidraw_control.py", line 267, in <module>
    e = AxiDrawWrapperClass()
  File "axidraw_control.py", line 62, in __init__
    self.OptionParser.add_option_group(
AttributeError: 'AxiDrawWrapperClass' object has no attribute 'add_option_group'

**Comment by oskay** [comment]
If you're an AxiDraw owner, please use our contact form ( https://shop.evilmadscientist.com/contact )-- we do have a beta version available with Inkscape V1 support.  We'll be releasing more of it in this repository and in our public download links as we get more comfortable supporting it.

The method that you're using will not be supported.
