### ISSUE TITLE
Control the speed between two coordinates

### ISSUE THREAD

**Issue by amelie1998** [evil-mad/axidraw#79]
Hi! Is it possible to control precisely the speed of the robot. I want to plot a set of coordinates with a variety of speed between each one of them. The coordinates were taken at a sample rate stable, but the length of the path between them is different. Can I control the speed directly with the API ? Or with the time between each set of coordinates ?

**Comment by oskay** [comment]
There is no facility for doing this while plotting a single SVG document. The EBB command protocol can be used to draw segments with different durations, or even with acceleration, but you should keep in mind that not all speed combinations are possible.

http://evil-mad.github.io/EggBot/ebb.html#commands

If you are using the AxiDraw python library in the [interactive context](https://axidraw.com/doc/py_api/#quick-start-interactive-xy), you can individually control the speed of each segment that you draw.

**Comment by amelie1998** [comment]
Thank you for your response ! It's exactly what I was looking for !

**Comment by ambare98** [comment]
Hi! I'm working with the "Low-Level Move" and "Stepper Move" command and I've got some issues with the movement. I send only command for the movement in one axis, but the robot keeps moving in diagonal (45 degrees). 
When I use the AxiDraw python library and I set the movement to only one direction, it works. So I checked the commands that are sent through the USB port to the robot and the "Stepper Move" command is used. However, even though the robot only goes in one direction, the command gives information for both axis. Is it normal ? How can I adjust that ?

**Comment by oskay** [comment]
@ambare98 This sounds like an unrelated question. 

If you have an issue to describe, related to this one, then this is a reasonable place to ask it. If it is unrelated (as this appears to be), it is *inappropriate* to ask it here. If you have a new question, open a new issue, or contact tech support directly.
