### ISSUE TITLE
How to set the step scale per mm?

### ISSUE THREAD

**Issue by Veilkrand** [evil-mad/axidraw#87]
I guess this is a question more related to the firmware commands. I'm currently using `EB Firmware Version 2.6.5` 
Is there a command or settings I can change the step scale? I want to calibrate the steps per mm for both motors or individual ones if possible.

Thanks

**Comment by oskay** [comment]
Yes, the [EM](http://evil-mad.github.io/EggBot/ebb.html#EM) command.

**Comment by Veilkrand** [comment]
Is this configuration integrated at high level when using pyaxidraw or the cli? Thanks

**Comment by oskay** [comment]
Yes.

**Comment by Veilkrand** [comment]
I mean, is it possible to configure the scale using the pyaxidraw API?

**Comment by oskay** [comment]
Yes.
