### ISSUE TITLE
res_plot not working

### ISSUE THREAD

**Issue by stephanschulz** [evil-mad/axidraw#89]
I am on macOS 10.14.6 and have successfully installed the API. 
I can start a SVG plot via the axicli commands.

I am now trying to pause the plot via the physical button. But resuming does not work. 
Is it possible that the temp.svg can't be created on my OS?

Thanks for any advice.

```
Stephan-2:output_svg stephanschulz$ axicli maskPG_2_outline.svg --report_time --speed_pendown 50 --accel 55 --pen_pos_down 51 --pen_pos_up 65 --no_rotate
Plot paused by button press.
Use the resume feature to continue.
Elapsed time: 00:01 (minutes, seconds)
Length of path drawn: 0.11 m.
Total distance moved: 0.11 m.
Stephan-2:output_svg stephanschulz$ axicli temp.svg --mode res_plot
Input file required but not found. For help, try:
    axicli --help
Stephan-2:output_svg stephanschulz$ axicli maskPG_2_outline.svg --mode res_plot 
No in-progress plot data found in file.
Stephan-2:output_svg stephanschulz$ 
```

**Comment by stephanschulz** [comment]
now I understand that I need to add a `-o output.svg` to the command line. only then can I use the resume function successfully. 
`axicli maskPG_2_outline.svg --report_time --speed_pendown 50 --accel 55 --pen_pos_down 51 --pen_pos_up 65 --no_rotate --model 2 -o output.svg`

**Comment by oskay** [comment]
Two notes:
* Since you're using a lot of CLI options, you might prefer to use a [config file](https://axidraw.com/doc/cli_api/#config) for most of them.
* Settings like speed and pen positions are not saved within the SVG file. Unless you intentionally want to use different settings for the second part of the plot, you should probably call the same options when you resume.

**Comment by stephanschulz** [comment]
Thanks for the tips.
I did notice the need to add again the speed and pen positions.

I am trying to expose a lot of the options via a processing.org sketch, so don't want to hide them in a config file.
I really like the trajectory estimation that comes with the API, which the axidraw processing library/examples does not have.
