### ISSUE TITLE
Make stand-alone (CLI) version of driver, that does not require Inkscape

### ISSUE THREAD

**Issue by oskay** [evil-mad/axidraw#9]
A CLI version of the extension would help make it possible to drive the AxiDraw without using Inkscape.  This could potentially improve performance (as Inkscape does not also need to parse and display the file), and enable things like "mail merge" type rapid-fire printing.

See https://github.com/hacktoon/ink2canvas for inspiration.

**Comment by oskay** [comment]
I have a first version of this up and running now. I could use a couple of beta testers.

**Comment by MattStultz** [comment]
I'm working on a project and this is exactly what I need, any chance I could take a look at your current driver?

**Comment by oskay** [comment]
Hi Matt,
We're currently testing this in private beta for AxiDraw users.

Please contact us directly (e-mail or contact form) and we can follow up.

**Comment by aarondfrancis** [comment]
I too would like to be included in this beta please.

**Comment by oskay** [comment]
Still in private beta, but now at second version --  rewritten with extensive docs available at:
https://axidraw.com/doc/cli_api/

**Comment by MattStultz** [comment]
Yay!

**Comment by oskay** [comment]
@MattStultz Please contact us by e-mail/contact form for the latest update.

**Comment by oskay** [comment]
https://axidraw.com/doc/cli_api/
