### ISSUE TITLE
OptionParser deprecated?

### ISSUE THREAD

**Issue by traiger** [evil-mad/axidraw#92]
I'm getting errors about OptionParser being deprecated and need to use ArgParser.

**Comment by oskay** [comment]
Can you please show the actual error that you are getting, and describe what you are doing when you are getting it?

**Comment by oskay** [comment]
Closing for lack of details.

**Comment by traiger** [comment]
My mistake, I should have reported this in the 4xiDraw Extension for Inkscape.
