### ISSUE TITLE
hatch fill issue

### ISSUE THREAD

**Issue by supafur** [evil-mad/axidraw#95]
Hi,

i'm a french art teacher in highschool and we just pourchased an axidraw for our students.
I'm trying to improve my skills on inkscape during the christmas hollidays so i can help my students through their projects as soon as we will get back to work.

However, for now i'm using inkscape 10.0.1 on windows 10 and i can't figure how to resolve the follonwing issue. 

i've downloaded the eggbot extension and i would like to use crossatching to fill certain spaces in my drawing. unfortunatly i'm having the following error message, wich i am not able to understand.

`eggbot_hatch.py:621: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:625: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:629: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:633: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:637: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:641: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:645: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:649: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
eggbot_hatch.py:653: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--tab",  # NOTE: value is not used.
eggbot_hatch.py:1736: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
eggbot_hatch.py:686: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  self.docTransform = simpletransform.parseTransform('scale({0:f},{1:f})'.format(sx, sy))
eggbot_hatch.py:1215: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  self.recursivelyTraverseSvg([self.selected[id_]], self.docTransform)
eggbot_hatch.py:818: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  mat_new = simpletransform.composeTransform(mat_current, simpletransform.parseTransform(node.get("transform")))
eggbot_hatch.py:818: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  mat_new = simpletransform.composeTransform(mat_current, simpletransform.parseTransform(node.get("transform")))
eggbot_hatch.py:894: DeprecationWarning: simplepath.formatPath -> str(element.path) or str(Path(array))
  self.addPathVertices(simplepath.formatPath(a), node, mat_new)
Traceback (most recent call last):
  File "eggbot_hatch.py", line 1736, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\deprecated.py", line 181, in affect
    return self.run(args=args)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "eggbot_hatch.py", line 1215, in effect
    self.recursivelyTraverseSvg([self.selected[id_]], self.docTransform)
  File "eggbot_hatch.py", line 894, in recursivelyTraverseSvg
    self.addPathVertices(simplepath.formatPath(a), node, mat_new)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\deprecated.py", line 258, in _inner
    return func(*args, **kwargs)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\deprecated-simple\simplepath.py", line 36, in formatPath
    return str(Path(a))
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\paths.py", line 1091, in __init__
    self.append(PathCommand.letter_to_class(item[0])(*item[1]))
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\paths.py", line 111, in letter_to_class
    return PathCommand._letter_to_class[letter]
KeyError: 'M '`

if some of you was able to bring me some help, i'd be very thankfull

ps : sorry for my broken english, doing my best here

**Comment by oskay** [comment]
I'm not sure what all of the errors are, but the first "DeprecationWarning" indicates that the software is not installed correctly. 

That is to say, you are either running an older version of the AxiDraw/EggBot software (not compatible with Inkscape 1.0) or you have installed only part of the software. 

If you're running Inkscape 1.0, then I recommend to follow the current installation instructions for the full AxiDraw software package: https://wiki.evilmadscientist.com/Axidraw_Software_Installation

**Comment by supafur** [comment]
thank you very mutch for your answer.
effectivelty, i confused the axidraw and the eggbot software
