### ISSUE TITLE
axidrawinternal not listed in dependencies

### ISSUE THREAD

**Issue by x37v** [evil-mad/axidraw#98]
The README says 
```
Manual install (Linux):

Install (along with the dependencies listed below) as you would any other Inkscape extension.

Dependencies:

    plotink helper routines for Inkscape extensions.
    eggbot_hatch.py from the EggBot extensions for Inkscape.
    Pyserial. (Note that an older version, 2.7, must be used on Windows when using Inkscape 0.91 or older.)
```

When I put all that and the contents of `inkscape driver` into ` ~/.config/inkscape/extensions/` and then run the extension in inkscape I get an error
```
Traceback (most recent call last):
  File "axidraw_control.py", line 28, in <module>
    from axidrawinternal import axidraw   # https://github.com/evil-mad/axidraw
ModuleNotFoundError: No module named 'axidrawinternal'
```

Where does this come from? I see it in the release but not git. I guess I see something about it in the cli requirements.txt being on gitlab, is this not part of the open source shared code base?

**Comment by oskay** [comment]
Yes, the readme is out of date. 

If you would like to install a version that works in Inkscape, please use our release for Inkscape. 

The "active" parts for the 2.7.0 release are in this repository. There is some packaging and wrappers (including one that labels the main contents of this repository as "axidrawinternal") that is not maintained here. Those parts are included in the main download. Everything in the download (including the wrapper) is part of the open source release.

**Comment by x37v** [comment]
> Yes, the readme is out of date.
> 
> If you would like to install a version that works in Inkscape, please use our release for Inkscape.
> 
> The "active" parts for the 2.7.0 release are in this repository. There is some packaging and wrappers (including one that labels the main contents of this repository as "axidrawinternal") that is not maintained here. Those parts are included in the main download. Everything in the download (including the wrapper) is part of the open source release.

Ahh, okay thanks @oskay

**Comment by akx** [comment]
> There is some packaging and wrappers (including one that labels the main contents of this repository as "axidrawinternal") that is not maintained here.

Hmm – it looks like e.g. `eggbot_hatch.py` https://github.com/evil-mad/axidraw/blob/1b84dda355bc3bba8e4935e1fe6ea84a223e59df/inkscape%20driver/axidraw_hatch.inx#L6 comes from that repo..?

**Comment by oskay** [comment]
Is there a question?

**Comment by akx** [comment]
Sort of. It implies that this repo isn't fully usable on its own without the `axidrawinternal` bits.

**Comment by oskay** [comment]
The install bundle includes things from quite a few repositories.  For example, `eggbot_hatch.py` comes from  https://github.com/evil-mad/EggBot/blob/Inkscape_v1/inkscape_driver/eggbot_hatch.py

We do not have support for installing directly from the repository.

**Comment by akx** [comment]
Right - that seems a little complex, but alright. I presume the build process for the install bundle isn't open source?

**Comment by oskay** [comment]
All of the files in the open source release are open source. None of the installers, nor the scripts to build them, is open source.

**Comment by akx** [comment]
@oskay Thanks, that clarifies things. Happy holidays!
